name: GH Pipeline 01
on:
  push:
    paths:
      - '01-initial/**'
    branches:
      - main
      - dev
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: List Files
        run: ls -l

      - name: Confirm
        run: echo "pipeline is working"
  
